### ISSUE TITLE
How could we get the data of WikiKG90Mv2?

### ISSUE THREAD

**Issue by yuto3o** [uma-pi1/kgt5-context#1]
Reference mentioned on KGT5 homepage is not available now. Could you release this dataset again?

**Comment by AdrianKs** [comment]
Hi, OGB recently (re-)released text data for WikiKG90Mv2.
see [here](https://ogb.stanford.edu/docs/lsc/wikikg90mv2/) for information about the dataset
or [here for direct download of text data](http://snap.stanford.edu/ogb/data/lsc/mapping/wikikg90mv2_mapping.zip)

**Comment by yuto3o** [comment]
Thank you :)
