### ISSUE TITLE
FileNotFoundError in eval.py - "kgt5-context-wikidata5m/model.safetensors" Not Found

### ISSUE THREAD

**Issue by zebrahippo** [uma-pi1/kgt5-context#2]
**Description:**
Encountered a FileNotFoundError while executing the following command:
`python eval.py -m kgt5-context-wikidata5m/pytorch_model.bin -c kgt5-context-wikidata5m/config.yaml`

**Output：**
FileNotFoundError: No such file or directory: "kgt5-context-wikidata5m/model.safetensors"

**Comment by AdrianKs** [comment]
Hi, 
unfortunately I cannot reproduce this error. Can you try to download the checkpoint again from huggingface to ensure the downloaded checkpoint was not corrupted somehow.

**Comment by moritzblum** [comment]
Hi, I get the same error when trying to evaluate any of the provided checkpoints. All checkpoints are correctly downloaded from Huggingface, but there are no `model.safetensors` files provided.

**Comment by AdrianKs** [comment]
Hi, I added a safetensors version for the kgt5-context checkpoint, updated requirements, and added evaluation support for safetensors checkpoints.
Could you please try to evaluate the checkpoint with the newest version of the code and the specified requirements. 
You can evaluate with the following commands on the new converted checkpoint directly.
```
git lfs install
git clone https://huggingface.co/AdrianKs/kgt5-context-wikidata5m

python eval.py -m kgt5-context-wikidata5m/model.safetensors -c kgt5-context-wikidata5m/config.yaml
```

Please let me know if this fixes your issue.
If it does, I will add safetensor versions to the other checkpoints as well.

**Comment by moritzblum** [comment]
The model is loaded successfully, and the evaluation works. Thank you!

**Comment by AdrianKs** [comment]
Great `model.safetensors` should be available for all checkpoints now.
